# syntax=docker/dockerfile:1.7
FROM rust:1.92.0-bookworm@sha256:e90e846de4124376164ddfbaab4b0774c7bdeef5e738866295e5a90a34a307a2 AS build
WORKDIR /source
ENV CARGO_INCREMENTAL=0
COPY Cargo.toml Cargo.lock rust-toolchain.toml ./
COPY src ./src
RUN cargo build --locked --release --bin hybrid-x509-evaluate

FROM debian:bookworm-slim@sha256:abd67ffcfa541b485a3dff59865ab629aa048a6c613e639d36e7456b0b229241
COPY --from=build /source/target/release/hybrid-x509-evaluate /usr/local/bin/hybrid-x509-evaluate
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/hybrid-x509-evaluate"]
