FROM golang:1.26.6-bookworm@sha256:116d58cbd88c1297624acc6e967a060012422bacf9930927e23fb719189c6f36 AS build
WORKDIR /source
COPY go.mod *.go ./
RUN go test ./... && CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -buildid=" -o /adapter .

FROM scratch
COPY --from=build /adapter /adapter
USER 65532:65532
ENTRYPOINT ["/adapter"]
